markdown: 'redcarpet'
pygments: true
permalink: 'pretty'
title: '• mk_blog •'
tagline:
description: '<a href=/><img class=brand src=/public/mk.png /></a>'
url: '/'
author:
  name: 'kresimir pendic'
  url: 'https://twitter.com/mkdizajn'
paginate: 4
version: '1.0.1'
github:
  repo: 'http://git.io/AdS8ew'
prose:
  media: 'media'
  #rooturl: '_posts'
  siteurl: 'http://mkdizajn.github.io/'
  metadata:
  	.:
      - name: 'layout'
        field:
          element: 'select'
          options: 
          	- name: 'post'
              value: 'post'
            - name: 'page'
              value: 'page'
      - name: 'published'
        field:
          element: 'hidden'
          value: 'true'
      - name: 'title'
        field:
          element: 'text'
          value: 'My new title'
      - name: 'excerpt'
        field:
          element: 'textarea'
          label: 'excerpt'
          placeholder: 'enter your excerpt text. sean before post..'
          value: 'My new teaser text'
      - name: 'backgroundpic'
        field:
          element: 'text'
          label: 'insert path to uploaded image'
          placeholder: 'url path from public ..'
          value: 'http://mkdizajn.github.io/public/ ..'
      - name: 'tags'
        field:
          element: 'multiselect'
          label: 'Add Tags'
          placeholder: 'Choose Tags'
          alterable: true
          options: 'http://mkdizajn.github.io/public/my-cats.jsonp'
